new ht 6
VitaliiVinn/JAVA pull request #4
Opened 2023-01-14 07:04 UTC by VitaliiVinn

2023-01-15 20:12 UTC, IIUPAMET approved these changes

2023-01-15 20:12 UTC, IIUPAMET commented on automationJava/homework6/Person.java
> +        return "Громадянин " + name + " " + surname + " телефонує громадянину " + person.name + " " + person.surname +
бажано використовувати this.name коли ми працюємо з полями классу, не є грубою помилкою і в майбутньому може залежити від проекту де працюєте

2023-01-23 08:14 UTC, Vladyslavtovkun requested changes

2023-01-23 08:14 UTC, Vladyslavtovkun commented on automationJava/homework8/MainStudent.java
> +        Student student = new Student("Bill", 3);
краще почати назву з Student1, щоб небуло плутанини

2023-01-23 08:14 UTC, Vladyslavtovkun commented on automationJava/homework8/Student.java
> +    //    Створити клас Student, що містить такі характеристики – ім’я, курс.
Видалить будь-ласка коментарі, або якщо вам зручніше, напишить їх над классом. Я показував на початку останньої лекції як це зробити

2023-01-24 16:43 UTC, merged